include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    public_member_api_docs: warning

linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types
    - prefer_final_locals
